// Generated by CoffeeScript 1.12.5
(function() {
  $(function() {
    var $caption, $image, $overlay;
    $overlay = $('<div id="overlay"></div>');
    $image = $('<img>');
    $caption = $('<p></p>');
    $overlay.append($image);
    $overlay.append($caption);
    $('body').append($overlay);
    $('#gallery a').click(function(event) {
      var caption, url;
      event.preventDefault();
      url = $(this).attr('href');
      $image.attr('src', url);
      caption = $(this).children('img').attr('alt');
      $caption.text(caption);
      return $overlay.show();
    });
    return $overlay.click(function() {
      return $overlay.hide();
    });
  });

}).call(this);
